services:
  db:
    image: mysql:8.4.2
    environment:
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_DATABASE: todo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - todo-db-data:/var/lib/mysql
    ports:
      - "33306:3306"
volumes:
  todo-db-data:
