services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/go/pkg/mod
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: todo
      DB_PASSWORD: todo
      DB_NAME: todo
    depends_on:
      - db

  db:
    image: mysql:8.4.2
    environment:
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_DATABASE: todo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - todo-db-data:/var/lib/mysql
    ports:
      - "33306:3306"
volumes:
  todo-db-data:
