linters-settings:
  gocyclo:
    min-complexity: 30
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - gocognit
    - gocritic
    - gofmt
    - goimports
    - govet
    - misspell
    - staticcheck
    - unused
    - whitespace
