name: backend-lint
on:
  pull_request:
    paths:
      - "**.go"
      - .github/workflows/backend-lint.yml
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: backend/
          reporter: "github-pr-review"
          fail_on_error: true
