name: frontend-lint
on:
  pull_request:
    paths:
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.ts"
      - "**/*.tsx"
      - .github/workflows/frontend-lint.yml
      - frontend/eslint.config.js
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           workdir: frontend/
           reporter: github-pr-review
           fail_on_error: true
