name: frontend-lint
on:
  pull_request:
    paths:
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.ts"
      - "**/*.tsx"
      - .github/workflows/frontend-lint.yml
      - frontend/biome.json
jobs:
  biome-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: ""
          working-dir: "frontend"

      - name: Run Biome
        run: biome ci .
